"""
GNU License or generic module header.
Author: Nick Hobar
Creation date: 09/18/2026
Description: The generated files beside the served models: the client
             manifest, credits.json and CREDITS.md.

             Nobody edits these by hand. The build writes them from the model
             records and the source records, and the check fails when the
             committed copy differs from a fresh render.

             THE MANIFEST is {asset_key: "family/file.glb"}, for every key AND
             every alias. An alias points at the file of its model, so four
             keys cost one download. The shape is unchanged since 08/25/2026:
             a bare path and no presentation, because how a model is shown is
             the client's own fact (ModelRegistry.PRESENTATION).

             THE CREDITS come from the source records, one entry for each
             source that a served model uses. CC-BY asks for a credit that
             follows the work, so the Godot client shows credits.json in the
             Options pane. CREDITS.md is the same list for a person who reads
             the repository or the served tree.
"""

import json
import os

from assets.pipeline import licenses, paths, records, sources


# ─── Private constant definitions ────────────────────────────────────────────

_MARKDOWN_HEADER: str = """# Model credits

Every model served from this directory, and the license it arrived under.

**Generated. Do not edit this file.** `python -m assets.pipeline build` writes
it from the source records in `assets/sources/*/source.toml`. Change a credit
there. The Godot client shows the same list, from `credits.json`, in the
Options pane.
"""

_EXCEPTION_MARK: str = "**License not confirmed.**"


# ─── Private helper routines ─────────────────────────────────────────────────

def _served_records(all_records: list) -> list:
    """
    Purpose: Keep the records whose served file exists.

    Entry:
        all_records holds loaded ModelRecords.

    Exit/Returns:
        Returns the records with a .glb in the served tree, in input order.

    Module Globals:
        None.

    Methodology:
        A manifest row that names a missing file sends every client to a 404,
        which is the failure the manifest exists to prevent.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    served = []

    for record in all_records:
        path = paths.served_path(record.family, record.asset_key)

        if os.path.isfile(path):
            served.append(record)

    return served


def _credit_entry(source: sources.Source, keys: list) -> dict:
    """
    Purpose: Give the credit of one source, as credits.json stores it.

    Entry:
        source is loaded. keys holds every asset key the source serves.

    Exit/Returns:
        Returns a dict with the fields the Godot credits box reads.

    Module Globals:
        None.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    terms = licenses.terms_for(source.license)

    return {
        "title": source.title,
        "author": source.author,
        "url": source.url,
        "license": terms.name,
        "license_url": terms.url,
        "confirmed": not source.exception,
        "models": sorted(keys),
    }


def _markdown_section(entry: dict) -> str:
    """
    Purpose: Render one credit as a CREDITS.md section.

    Entry:
        entry has the shape _credit_entry returns.

    Exit/Returns:
        Returns the section text, ending in a blank line.

    Module Globals:
        _EXCEPTION_MARK read.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    license_text = entry["license"]

    if entry["license_url"]:
        license_text = "[%s](%s)" % (entry["license"], entry["license_url"])

    lines = ["## %s" % entry["title"], "",
             "- Author: %s" % entry["author"],
             "- Source: %s" % entry["url"],
             "- License: %s" % license_text,
             "- Models: %s" % ", ".join("`%s`" % key
                                        for key in entry["models"])]

    if not entry["confirmed"]:
        lines.append("- %s See the source record for the reason."
                     % _EXCEPTION_MARK)

    return "\n".join(lines) + "\n"


# ─── Public routines ─────────────────────────────────────────────────────────

def render_manifest(all_records: list) -> dict:
    """
    Purpose: Build the client manifest.

    Entry:
        all_records holds loaded ModelRecords.

    Exit/Returns:
        Returns {asset_key: "family/asset_key.glb"}, sorted by key, for every
        key and alias of every record whose served file exists.

    Module Globals:
        None.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    entries = {}

    for record in _served_records(all_records):
        relative = paths.served_relative(record.family, record.asset_key)

        for key in record.keys:
            entries[key] = relative

    return dict(sorted(entries.items()))


def render_credits(all_records: list) -> list:
    """
    Purpose: Build the credits list.

    Entry:
        all_records holds loaded ModelRecords. Every source they name loads.

    Exit/Returns:
        Returns one entry for each source a served model uses, sorted by
        title. Raises sources.SourceError for a source that does not load.

    Module Globals:
        None.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    keys_by_source = {}

    for record in _served_records(all_records):
        keys = keys_by_source.setdefault(record.source_id, [])
        keys.extend(record.keys)

    entries = []

    for source_id, keys in keys_by_source.items():
        source = sources.load_source(source_id)
        entry = _credit_entry(source, keys)
        entries.append(entry)

    entries.sort(key=lambda item: item["title"].lower())

    return entries


def render_markdown(credits: list) -> str:
    """
    Purpose: Render the credits list as CREDITS.md.

    Entry:
        credits has the shape render_credits returns.

    Exit/Returns:
        Returns the whole file, ending in one newline.

    Module Globals:
        _MARKDOWN_HEADER read.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    sections = [_markdown_section(entry) for entry in credits]
    body = "\n".join(sections)

    return _MARKDOWN_HEADER + "\n" + body


def render_all() -> dict:
    """
    Purpose: Render every generated file from the records on disk.

    Entry:
        No conditions.

    Exit/Returns:
        Returns {absolute path: file text}. Raises records.RecordError or
        sources.SourceError for a bad record.

    Module Globals:
        paths.CLIENT_MANIFEST_PATH, paths.CREDITS_JSON_PATH,
        paths.CREDITS_MARKDOWN_PATH read.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    all_records = records.load_all()
    manifest = render_manifest(all_records)
    credits = render_credits(all_records)
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    credits_text = json.dumps(credits, indent=2, ensure_ascii=False) + "\n"
    markdown_text = render_markdown(credits)

    return {paths.CLIENT_MANIFEST_PATH: manifest_text,
            paths.CREDITS_JSON_PATH: credits_text,
            paths.CREDITS_MARKDOWN_PATH: markdown_text}


def write_all() -> list:
    """
    Purpose: Write every generated file.

    Entry:
        No conditions.

    Exit/Returns:
        Returns the paths written. Each file is UTF-8 with LF line endings.

    Module Globals:
        None.

    Author: Nick Hobar
    Creation date: 09/18/2026
    """
    rendered = render_all()

    for path, text in rendered.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)

        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)

    return sorted(rendered)
