"""
GNU License or generic module header.
Author: Nick Hobar
Creation date: 09/24/2026
Description: The fixed facts of the tile grid: the chunk size, the walk flag
             bits, the directions, and the limits of the path search.

             DESIGN-0011 section 6 is the design. This module is the Phase 1
             spike. Nothing live uses it yet.
"""

# ─── Chunk shape ─────────────────────────────────────────────────────────────

# Tiles along one side of a chunk. DESIGN-0011 decision: at least 64, like an
# OSRS map square.
CHUNK_SIZE: int = 64

# Corner heights along one side of a chunk. A tile has a height at each of its
# four corners, so a row of CHUNK_SIZE tiles has one more corner than tiles.
CORNERS_PER_SIDE: int = CHUNK_SIZE + 1

# The height of a new corner, in height steps.
DEFAULT_HEIGHT: int = 0

# The floor type index of a new tile. Index 0 of a chunk's floor names.
DEFAULT_FLOOR: int = 0

# ─── Walk flags ──────────────────────────────────────────────────────────────
# One int for each tile. A bit limits movement on the tile or across one edge.
# A wall sits on the edge of a tile. A step across an edge is refused if a wall
# is on either side of it, so an author can paint a wall on one tile only.

FLAG_NONE: int = 0
FLAG_BLOCKED: int = 1 << 0
FLAG_WATER: int = 1 << 1
FLAG_WALL_NORTH: int = 1 << 2
FLAG_WALL_EAST: int = 1 << 3
FLAG_WALL_SOUTH: int = 1 << 4
FLAG_WALL_WEST: int = 1 << 5

# A tile with any of these bits holds no player.
FLAGS_UNWALKABLE: int = FLAG_BLOCKED | FLAG_WATER

# The four wall bits. The path search reads them inline. A step that touches
# no wall and no unwalkable tile needs no call to `check_step`.
FLAGS_WALLS: int = (FLAG_WALL_NORTH | FLAG_WALL_EAST | FLAG_WALL_SOUTH
                    | FLAG_WALL_WEST)

# Every defined bit. A chunk file with a bit outside this mask is refused, so
# a typo in the editor cannot store a flag that no reader knows.
FLAGS_ALL: int = (FLAG_BLOCKED | FLAG_WATER | FLAG_WALL_NORTH | FLAG_WALL_EAST
                  | FLAG_WALL_SOUTH | FLAG_WALL_WEST)

# ─── Chunk file ──────────────────────────────────────────────────────────────
# DESIGN-0011 section 6.2. `chunkfile.py` reads and writes it in Python, and
# `godot/world/terrain/chunk_file.gd` in GDScript. Both readers read these
# values from one place: the GDScript copy is generated by
# `scripts/export_client_constants.py`.

# The format version. A reader refuses any other value.
CHUNK_FORMAT_VERSION: int = 1

# The highest plane. Plane 0 is the ground. OSRS has four planes, 0 to 3.
PLANE_MAX: int = 3

# The ground plane. Its rooms have the Z WORLD_Z, as before planes.
GROUND_PLANE: int = 0

# The room Z of a plane above the ground (Phase 7). `planes.plane_z` fills
# it. The pool of a plane adds POOL_Z_SUFFIX, which no plane Z matches.
PLANE_Z_TEMPLATE: str = "{world}_p{plane}"

# The range of a corner height, in height steps: a signed 16-bit int.
HEIGHT_MIN: int = -32768
HEIGHT_MAX: int = 32767

# An object turns in quarter turns, 0 to 3, as an OSRS object does.
ROTATION_COUNT: int = 4

# A floor name, an area name, and an object kind. Lower case, digits, and
# underscores. Thus, no name needs a JSON escape, and the two writers cannot
# escape a name differently.
CHUNK_NAME_PATTERN: str = "^[a-z0-9_]+$"

# The file name of a chunk file, and the directory of the world, from the
# game directory.
CHUNK_FILE_TEMPLATE: str = "chunk_{cx}_{cy}_p{plane}.json"
CHUNK_DIRECTORY: str = "world/chunks"

# The tile sync stamp, from the game directory: a digest of each chunk file at
# the last `sync_tile_objects.py --apply` (`syncstamp.py`). It describes the
# dev database, so it lives beside it, and git ignores it. The terrain editor
# reads it to name the chunk files that changed since.
SYNC_STAMP_FILE: str = "server/tile_sync_state.json"

# The chunks around the chunk of a player that the server sends and the client
# keeps, on each side. 1 gives a 3 x 3 block, as DESIGN-0011 section 6.6 says.
# The client frees a chunk outside the block.
STREAM_RADIUS_CHUNKS: int = 1

# ─── Object categories ───────────────────────────────────────────────────────
# What sort of thing a placed object is. `world/object_kinds.py` gives each
# kind one category. The editor groups and colours its markers by category, so
# the client export carries the vocabulary. A transition moves a walker to another tile, as a
# `MapTransitionNode` of the xyzgrid does. A landmark names its tile and
# stands nothing up, for example the respawn point.

OBJECT_CATEGORY_FACILITY: str = "facility"
OBJECT_CATEGORY_GATHERING: str = "gathering"
OBJECT_CATEGORY_LANDMARK: str = "landmark"
OBJECT_CATEGORY_NPC: str = "npc"
OBJECT_CATEGORY_SIGN: str = "sign"
OBJECT_CATEGORY_TRANSITION: str = "transition"
OBJECT_CATEGORY_CLIMB: str = "climb"

OBJECT_CATEGORIES: tuple = (
    OBJECT_CATEGORY_CLIMB,
    OBJECT_CATEGORY_FACILITY,
    OBJECT_CATEGORY_GATHERING,
    OBJECT_CATEGORY_LANDMARK,
    OBJECT_CATEGORY_NPC,
    OBJECT_CATEGORY_SIGN,
    OBJECT_CATEGORY_TRANSITION,
)

# ─── Climbing (Phase 7) ──────────────────────────────────────────────────────
# A climb object (a ladder, stairs) moves a walker who stands on its tile to
# the same tile one plane up or down (Nick, 09/26/2026). Each climb kind lists
# its directions. The words are the words that a player types after `climb`.
CLIMB_UP: str = "up"
CLIMB_DOWN: str = "down"

# The plane change of each direction.
CLIMB_PLANE_STEPS: dict = {
    CLIMB_UP: 1,
    CLIMB_DOWN: -1,
}

# ─── Directions ──────────────────────────────────────────────────────────────
# Y grows to the north, as on the xyzgrid maps. A name is the word a player
# types. The names match the exit names of the xyzgrid contrib.

DIRECTION_OFFSETS: dict = {
    "north": (0, 1),
    "northeast": (1, 1),
    "east": (1, 0),
    "southeast": (1, -1),
    "south": (0, -1),
    "southwest": (-1, -1),
    "west": (-1, 0),
    "northwest": (-1, 1),
}

# The short word for each direction. An xyzgrid exit has the same aliases, so
# a player types the same words on both grids.
DIRECTION_ALIASES: dict = {
    "north": "n",
    "northeast": "ne",
    "east": "e",
    "southeast": "se",
    "south": "s",
    "southwest": "sw",
    "west": "w",
    "northwest": "nw",
}

# The wall bit on the edge that a cardinal step crosses, on the tile the step
# leaves. The tile it enters must have no wall on the opposite edge.
EDGE_WALL_LEAVING: dict = {
    (0, 1): FLAG_WALL_NORTH,
    (1, 0): FLAG_WALL_EAST,
    (0, -1): FLAG_WALL_SOUTH,
    (-1, 0): FLAG_WALL_WEST,
}

EDGE_WALL_ENTERING: dict = {
    (0, 1): FLAG_WALL_SOUTH,
    (1, 0): FLAG_WALL_WEST,
    (0, -1): FLAG_WALL_NORTH,
    (-1, 0): FLAG_WALL_EAST,
}

# ─── Step results ────────────────────────────────────────────────────────────
# What `TileGrid.check_step` returns. A caller picks the message for the
# player from the result, so the grid module holds no player text.

STEP_OK: str = "ok"
STEP_NOT_ADJACENT: str = "not_adjacent"
STEP_OFF_GRID: str = "off_grid"
STEP_BLOCKED: str = "blocked"
STEP_WALL: str = "wall"
STEP_CORNER: str = "corner"
STEP_TOO_STEEP: str = "too_steep"

# Evennia refused the move itself, for example a lock or an `at_pre_move`.
STEP_MOVE_REFUSED: str = "move_refused"

# ─── Height rule ─────────────────────────────────────────────────────────────
# The largest height change, in height steps, that one step may climb or drop.
# A bigger change is a cliff. None means no limit. The rule is in the Obsidian
# vault, 03_Systems/Movement_and_Traversal.md, "Height and the walk limit"
# (Nick, 09/26/2026). 16 steps is one tile of rise over one tile of run.
WALK_LIMIT = 16

# ─── Line of sight ───────────────────────────────────────────────────────────
# The tile flags that stop a shot on a tile that the line enters. Water does
# not stop a shot, and neither does height. A wall stops a shot on its own
# edge. The rule is in the Obsidian vault, 03_Systems/Combat_System.md, "Line
# of sight" (Nick, 09/26/2026).
FLAGS_BLOCK_SIGHT: int = FLAG_BLOCKED

# The fraction bits of the fixed-point line of the sight walk. OSRS uses 16.
# Integers, not floats, so the Python and a later GDScript walk agree.
SIGHT_FIXED_POINT_BITS: int = 16

# ─── Path search ─────────────────────────────────────────────────────────────
# The most tiles that one search may expand before it gives up. A search that
# cannot reach its goal expands every tile it can reach, so this bounds the
# cost of a `goto` to a walled-off tile. One chunk of tiles. OSRS also limits
# its path search to the loaded scene. The spike measured 78 ms at four
# chunks, which one click must not cost.
PATH_MAX_EXPANDED: int = CHUNK_SIZE * CHUNK_SIZE

# ─── Rooms ───────────────────────────────────────────────────────────────────
# The Z of every tile room on the tile grid. The xyzgrid stores a map name in
# Z. The tile grid is one world, so it has one name.
WORLD_Z: str = "tile_world"

# Added to the Z of a world to make the Z of its pool. A pooled room keeps its
# old x and y tags and gets this Z. No search on the Z of the world finds it,
# and a move out of the pool changes as few tags as possible. The spike
# measured a full retag at 47 queries for each step.
POOL_Z_SUFFIX: str = "_pool"

# The most empty rooms that the pool keeps. A room released past this count is
# deleted. The spike measures a pool of this size against no pool at all.
POOL_CAPACITY: int = 64

# The ticks between two sweeps of the live rooms. A step and `place` give an
# empty room back at once. A teleport, a logout, and a delete do not, so the
# sweep collects those rooms. 100 ticks is 60 seconds. An empty room costs
# one row and one index entry until then, so the sweep need not be fast.
SWEEP_EVERY_TICKS: int = 100

# The key of every tile room. A pooled room moves from tile to tile, so a key
# with the coordinates in it would need a write on each move. Phase 4 decides
# what name a player sees, for example the area name.
ROOM_KEY: str = "tile"
